const data = [{
    "id": 1,
    "first_name": "Quintina",
    "last_name": "Slany",
    "email": "qslany0@reuters.com",
    "gender": "Female",
    "ip_address": "26.16.10.231",
    "address": "Tai Po",
    "photo": "images/Wom.png",
    "company": "Kwilith",
    "department": "Services",
    "movies": "4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamâni si 2 zile)",
    "about": "ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet"
},
    // , {
    //     "id": 2,
    //     "first_name": "Sigismundo",
    //     "last_name": "Oboy",
    //     "email": "soboy1@cornell.edu",
    //     "gender": "Male",
    //     "ip_address": "179.76.60.195",
    //     "address": "Rancaranji",
    //     "photo": "https://robohash.org/utquasicorrupti.bmp?size=50x50&set=set1",
    //     "company": "Yabox",
    //     "department": "Sales",
    //     "movies": "33 Postcards",
    //     "about": "ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices"
    // }, {
    //     "id": 3,
    //     "first_name": "Dannye",
    //     "last_name": "Devenport",
    //     "email": "ddevenport2@alibaba.com",
    //     "gender": "Female",
    //     "ip_address": "54.99.71.1",
    //     "address": "Calilegua",
    //     "photo": "https://robohash.org/dolorumsedqui.png?size=50x50&set=set1",
    //     "company": "Yabox",
    //     "department": "Services",
    //     "movies": "Earth Girls Are Easy",
    //     "about": "mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue"
    // }, {
    //     "id": 4,
    //     "first_name": "Lorens",
    //     "last_name": "McAlinden",
    //     "email": "lmcalinden3@bizjournals.com",
    //     "gender": "Male",
    //     "ip_address": "105.254.37.138",
    //     "address": "Cincinnati",
    //     "photo": "https://robohash.org/facereeteligendi.jpg?size=50x50&set=set1",
    //     "company": "Zoozzy",
    //     "department": "Services",
    //     "movies": "Devil and Max Devlin, The",
    //     "about": "diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue"
    // },
];
export { data };